### PR TITLE
Update to swarm cli 0.19.1

### PR DESCRIPTION
**Pull request by gerrit-hntschl**
^

### CODE REVIEW

**Comment by zeisss** [comment]
Thanks :)

**Comment by gerrit-hntschl** [comment]
did you update the `kordless/giantswarm` step that is available on wercker? my deploy still complains that it is not using the 0.19.1 version and thus doesn't do anything

**Comment by zeisss** [comment]
Sorry, No I didn't.

@kordless Can you take care of this? I haven't used werker yet.

**Comment by gerrit-hntschl** [comment]
Looking at https://github.com/giantswarm/giantswarm-wercker-step/blob/master/run.sh#L14 the step won't work for services not named `swacker`, or is it?
Isn't `swarm status` sufficient?

**Comment by kordless** [comment]
PRs to Wercker steps must include a bump in version number for the step, otherwise the step won't be deployed to Wercker.  I'll bump the version now to address.

Regarding the second question, a `swarm status` will work as long as the service name isn't a variable in the swarm.json file. I've removed the service name from the script with 93f613ecbd28e3c30c19101a45b8d31b2e73cf50.

Please feel free to open an issue on any other problems you have with the step!

**Pull request merged**
